### ISSUE TITLE
test execution framework

### ISSUE THREAD

**Issue by brunonmachado** [rsommerard/defects4j#1]
Could you provide an example of test case execution using defects4j? I tried using the script framework/bin/run_mutation.pl ... but doesn´t work.. Could you help me use the defect4j for test case execution ?

**Comment by rsommerard** [comment]
Hi @brunonmachado,

The official defects4j repository is on https://github.com/rjust/defects4j.
You will have a better answer on it.

Maybe can you try with:

1) export defects4j bin
2) defects4j checkout -p Lang -v 1b -w lang_1
3) cd lang_1
4) defects4j compile
5) defects4j test

You can set DEBUG value to 1 on framework/core/Constants.pm to see more informations about test executions.
